# Generated by Django 3.0.3 on 2020-03-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0002_auto_20200310_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer')], default='Manager', max_length=20),
        ),
    ]
