# Generated by Django 3.0.3 on 2020-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomapp', '0003_auto_20200313_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Customer', 'Customer')], default='manager', max_length=20),
        ),
    ]
